"""comments

Revision ID: 3f5e48ef03c4
Revises: 6b2d15fed3f6
Create Date: 2024-12-24 16:44:21.002172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5e48ef03c4'
down_revision = '6b2d15fed3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('employee_name')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('emp_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emp_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
