"""sprint added create date

Revision ID: 526dbe1a4003
Revises: f16ba6f5d829
Create Date: 2024-12-09 15:49:08.401700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526dbe1a4003'
down_revision = 'f16ba6f5d829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
