"""project foreign key

Revision ID: 97bcfa058723
Revises: 3f5e48ef03c4
Create Date: 2025-01-07 13:57:27.101667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bcfa058723'
down_revision = '3f5e48ef03c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
