"""stage_id

Revision ID: c217c252a73e
Revises: af3dd1c8c6de
Create Date: 2024-11-14 13:48:59.769568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c217c252a73e'
down_revision = 'af3dd1c8c6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('stage_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key(None, 'stages', ['stage_id'], ['stage_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('stage_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
