"""project foreign key

Revision ID: c3a5b21aab8e
Revises: 97bcfa058723
Create Date: 2025-01-07 14:08:56.361804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a5b21aab8e'
down_revision = '97bcfa058723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
