"""Timelog ceation

Revision ID: 172d56e0a1c0
Revises: 43186a59262a
Create Date: 2025-04-22 14:48:17.544243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172d56e0a1c0'
down_revision = '43186a59262a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelog',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.Time(), nullable=True),
    sa.Column('clock_out', sa.Time(), nullable=True),
    sa.Column('total_hours', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timelog')
    # ### end Alembic commands ###
