"""migration message

Revision ID: 31c84e80dd88
Revises: ad68817b0b02
Create Date: 2025-03-04 16:19:33.105444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c84e80dd88'
down_revision = 'ad68817b0b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet',
    sa.Column('timesheet_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('projectName', sa.String(), nullable=True),
    sa.Column('jobName', sa.String(), nullable=True),
    sa.Column('workItem', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('totalHours', sa.Time(), nullable=True),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billable_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('timesheet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheet')
    # ### end Alembic commands ###
