"""added new fields in employees table

Revision ID: 3adeb434eaf6
Revises: 452be011977b
Create Date: 2024-11-11 12:09:51.573000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adeb434eaf6'
down_revision = '452be011977b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('organization', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('organization')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
