"""migration message

Revision ID: 43186a59262a
Revises: 4c0e874ff465
Create Date: 2025-04-07 11:39:47.066604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43186a59262a'
down_revision = '4c0e874ff465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint('timesheet_startDate_key', type_='unique')
        batch_op.drop_constraint('uq_start_date', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_start_date', ['startDate'])
        batch_op.create_unique_constraint('timesheet_startDate_key', ['startDate'])

    # ### end Alembic commands ###
