"""email changes

Revision ID: 7ca374f94f1d
Revises: 73f786940409
Create Date: 2025-06-30 12:52:28.955329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca374f94f1d'
down_revision = '73f786940409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(length=22), nullable=True))
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['task_id'], ondelete='SET NULL')

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_index('idx_leave_employee_id')
        batch_op.drop_index('idx_leave_start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.create_index('idx_leave_start_date', [sa.text('start_date DESC')], unique=False)
        batch_op.create_index('idx_leave_employee_id', ['employee_id'], unique=False)

    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
