"""email model

Revision ID: b6f7a2afdb73
Revises: 172d56e0a1c0
Create Date: 2025-05-29 16:34:20.055503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f7a2afdb73'
down_revision = '172d56e0a1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_notifications',
    sa.Column('notification_id', sa.String(length=22), nullable=False),
    sa.Column('employee_id', sa.String(length=22), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_notifications')
    # ### end Alembic commands ###
