"""task

Revision ID: f16ba6f5d829
Revises: c217c252a73e
Create Date: 2024-11-14 16:43:05.640540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16ba6f5d829'
down_revision = 'c217c252a73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('tasks_stage_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'stages', ['stage_id'], ['stage_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_stage_id_fkey', 'stages', ['stage_id'], ['stage_id'])

    # ### end Alembic commands ###
