"""Timehseet modal update

Revision ID: feeab57be713
Revises: 31c84e80dd88
Create Date: 2025-04-04 16:44:44.521691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feeab57be713'
down_revision = '31c84e80dd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_start_date', ['startDate'])
        batch_op.create_unique_constraint(None, ['startDate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_start_date', type_='unique')

    # ### end Alembic commands ###
